apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-apptwo-api-deployment
  namespace: dotnetcore
  labels:
    app: service-apptwo-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-apptwo-api
  template:
    metadata:
      labels:
        app: service-apptwo-api
    spec:
      containers:
      - name: service-apptwo-api-demo
        image: 	shaohz/k8s-service-apptwo
        ports:
        - containerPort: 80

---

kind: Service
apiVersion: v1
metadata:
  name: k8s-service-apptwo
  namespace: dotnetcore
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: service-apptwo-api
